import PDFDocument from 'pdfkit';
import { Response } from 'express';
import { IFee } from '../models/Fee';
import { IUser } from '../models/User';

export const generateFeeReceipt = (res: Response, fee: any, user: any) => {
    const doc = new PDFDocument({ margin: 50 });

    // Stream PDF to response
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=receipt_${fee.receiptNumber || fee._id}.pdf`);
    doc.pipe(res);

    // --- Header ---
    doc.fillColor('#4f46e5').fontSize(24).text('SHAMS HOSTEL', { align: 'center' });
    doc.fillColor('#6b7280').fontSize(10).text('Smart Hostel Management System', { align: 'center' });
    doc.moveDown();
    doc.strokeColor('#e5e7eb').moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown();

    // --- Receipt Info ---
    doc.fillColor('#111827').fontSize(18).text('PAYMENT RECEIPT', { align: 'left' });
    doc.moveDown(0.5);
    
    const yStart = doc.y;
    doc.fontSize(10).fillColor('#6b7280');
    doc.text(`Receipt No: ${fee.receiptNumber || 'N/A'}`, 50, yStart);
    doc.text(`Date: ${new Date(fee.lastPaymentAt || fee.updatedAt).toLocaleDateString()}`, 50, yStart + 15);
    doc.text(`Academic Year: ${fee.academicYear || new Date().getFullYear()}`, 50, yStart + 30);

    doc.text('BILL TO:', 350, yStart);
    doc.fillColor('#111827').font('Helvetica-Bold');
    doc.text(user.name.toUpperCase(), 350, yStart + 15);
    doc.font('Helvetica').fillColor('#6b7280');
    doc.text(`Student ID: ${user.profile?.studentId || 'N/A'}`, 350, yStart + 30);
    doc.text(`Email: ${user.email}`, 350, yStart + 45);

    doc.moveDown(4);

    // --- Table Header ---
    const tableTop = 230;
    doc.fillColor('#f9fafb').rect(50, tableTop, 500, 25).fill();
    doc.fillColor('#374151').font('Helvetica-Bold');
    doc.text('DESCRIPTION', 60, tableTop + 7);
    doc.text('CATEGORY', 250, tableTop + 7);
    doc.text('MODE', 380, tableTop + 7);
    doc.text('AMOUNT', 480, tableTop + 7);

    // --- Table Row ---
    doc.font('Helvetica').fillColor('#111827');
    doc.text(fee.description || 'Hostel Fee Payment', 60, tableTop + 40);
    doc.text(fee.type, 250, tableTop + 40);
    doc.text(fee.paymentMode || 'ONLINE', 380, tableTop + 40);
    doc.text(`INR ${fee.paidAmount.toLocaleString()}`, 480, tableTop + 40);

    doc.moveDown(4);
    doc.strokeColor('#e5e7eb').moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown();

    // --- Summary ---
    const summaryY = doc.y;
    doc.fontSize(12).font('Helvetica-Bold').text('Total Paid:', 380, summaryY);
    doc.text(`INR ${fee.paidAmount.toLocaleString()}`, 480, summaryY);
    
    doc.fontSize(10).font('Helvetica').fillColor('#ef4444');
    doc.text('Balance Due:', 380, summaryY + 20);
    doc.text(`INR ${fee.balanceAmount.toLocaleString()}`, 480, summaryY + 20);

    // --- Footer ---
    doc.moveDown(10);
    doc.fillColor('#9ca3af').fontSize(8).text('This is a computer-generated receipt and does not require a physical signature.', { align: 'center' });
    doc.text('Generated by SHAMS ERP v1.0', { align: 'center' });

    doc.end();
};
