import { Request, Response } from 'express';
import asyncHandler from 'express-async-handler';
import Parcel from '../models/Parcel';
import User from '../models/User';
import { createNotification } from './notificationController';
import sendEmail from '../utils/sendEmail';

// Helper to generate random 4-6 digit code
const generatePickupCode = () => {
    return Math.floor(1000 + Math.random() * 9000).toString();
};

// @desc    Receive a new parcel/courier (Security)
// @route   POST /api/parcels
// @access  Private (Security/Admin)
export const receiveParcel = asyncHandler(async (req: any, res: Response) => {
    const { studentId, courierName, trackingId, notes } = req.body;

    if (!studentId || !courierName) {
        res.status(400);
        throw new Error('Student ID and Courier Name are required');
    }

    const student = await User.findOne({
        $or: [
            { _id: (studentId.match(/^[0-9a-fA-F]{24}$/) ? studentId : undefined) },
            { "profile.studentId": studentId }
        ]
    });

    if (!student) {
        res.status(404);
        throw new Error('Student not found with this ID');
    }

    const pickupCode = generatePickupCode();

    const parcel = await Parcel.create({
        student: student._id,
        courierName,
        trackingId,
        pickupCode,
        receivedBy: req.user._id,
        notes,
        arrivedAt: new Date(),
        status: 'Arrived'
    });

    // Notify Student
    await createNotification(
        student._id.toString(),
        '📦 New Parcel Arrived!',
        `A courier from ${courierName} has arrived. Pickup Code: ${pickupCode}`,
        'info'
    );

    // Send Email
    try {
        await sendEmail({
            email: student.email,
            subject: 'Smart HMS: New Parcel Arrived!',
            message: `Hi ${student.name}, A courier from ${courierName} has been received at the Security Gate.\n\nPickup Code: ${pickupCode}\n\nPlease visit the gate with your student ID to pick it up.`,
            html: `
                <div style="font-family: sans-serif; padding: 20px; border: 1px solid #ddd; border-radius: 10px;">
                    <h2 style="color: #4f46e5;">📦 New Parcel Arrival</h2>
                    <p>Hi <b>${student.name}</b>,</p>
                    <p>A courier has been received for you at the gate.</p>
                    <div style="background: #f3f4f6; padding: 15px; border-radius: 8px; margin: 20px 0;">
                        <p style="margin: 0; font-size: 14px; color: #6b7280;">Courier Service</p>
                        <p style="margin: 0; font-size: 18px; font-weight: bold; color: #111827;">${courierName}</p>
                        <hr style="border: 0; border-top: 1px solid #e5e7eb; margin: 10px 0;">
                        <p style="margin: 0; font-size: 14px; color: #6b7280;">Pickup OTP Code</p>
                        <p style="margin: 0; font-size: 32px; font-weight: 800; color: #4f46e5; letter-spacing: 4px;">${pickupCode}</p>
                    </div>
                    <p style="font-size: 14px; color: #ef4444;">Please do not share this code with anyone. Show this at the counter to receive your package.</p>
                    <p style="font-size: 12px; color: #9ca3af;">Auto-generated by Smart HMS Gate Management</p>
                </div>
            `
        });
    } catch (e) { console.error("Parcel email failed", e) }

    res.status(201).json(parcel);
});

// @desc    Get all parcels (Admin/Security) or filtered by student
// @route   GET /api/parcels
// @access  Private (Admin/Security)
export const getParcels = asyncHandler(async (req: any, res: Response) => {
    const { status, studentId } = req.query;

    let query: any = {};
    if (status) query.status = status;
    if (studentId) query.student = studentId;

    const parcels = await Parcel.find(query)
        .populate('student', 'name email profile.studentId profile.phone profile.roomNumber')
        .populate('receivedBy', 'name')
        .sort({ createdAt: -1 });

    res.json(parcels);
});

// @desc    Get my parcels (Student)
// @route   GET /api/parcels/my
// @access  Private (Student)
export const getMyParcels = asyncHandler(async (req: any, res: Response) => {
    const parcels = await Parcel.find({ student: req.user._id })
        .populate('receivedBy', 'name')
        .sort({ createdAt: -1 });
    res.json(parcels);
});

// @desc    Deliver parcel via Pickup Code (Security)
// @route   POST /api/parcels/:id/deliver
// @access  Private (Security/Admin)
export const deliverParcel = asyncHandler(async (req: any, res: Response) => {
    const { pickupCode } = req.body;

    if (!pickupCode) {
        res.status(400);
        throw new Error('Valid Pickup OTP code is required');
    }

    const parcel = await Parcel.findById(req.params.id);

    if (!parcel) {
        res.status(404);
        throw new Error('Parcel not found');
    }

    if (parcel.status === 'Delivered') {
        res.status(400);
        throw new Error('Parcel has already been delivered');
    }

    if (parcel.pickupCode !== pickupCode) {
        res.status(401);
        throw new Error('Invalid Pickup Code. Handover denied.');
    }

    parcel.status = 'Delivered';
    parcel.deliveredAt = new Date();
    await parcel.save();

    // Notify Student
    await createNotification(
        parcel.student.toString(),
        '🎁 Parcel Picked Up',
        `Your courier from ${parcel.courierName} has been successfully collected.`,
        'success'
    );

    res.json({ message: 'Handover Successful!', parcel });
});
